version: 2
general:
  artifacts:
    - coverage
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:8.10.0
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests
      - run: npm test
  coveralls:
    working_directory: ~/repo
    steps:
      - run: cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

workflows:
  version: 2
  build-and-cover:
    jobs:
      - build
      - coveralls:
        requires:
          - build
        filters:
          branches:
            only: master
